version: '3'

services:

  # database containers, one for each db
  database1:
    image: abhinav10p/postgresdj
    build: 
      dockerfile: Dockerfile.dev
      context: ./config/db
    volumes:
      - database1_volume:/var/lib/postgresql/data
    env_file:
      - config/db/database1_env
    networks:
      - db_network


  # web container, with django + gunicorn
  djangoapp:
    image: abhinav10p/djangoappdj:latest
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE
    volumes:
      - .:/opt/services/djangoapp/src
      - static:/opt/services/djangoapp/static
      - media:/opt/services/djangoapp/media
    networks:
      - db_network
      - nginx_network
    depends_on:
      - database1

  # reverse proxy container (nginx)
  nginx:
    image: abhinav10p/nginxdj
    build: 
      dockerfile: Dockerfile.dev
      context: ./config/nginx
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/opt/services/djangoapp/static
      - media:/opt/services/djangoapp/media
    networks:
      - nginx_network
    depends_on:
      - djangoapp

networks:
  db_network:
    driver: bridge
  nginx_network:
    driver: bridge

volumes:
  database1_volume:
  static:
  media:
